---
- name: Deploy GitHub Portfolio
  hosts: all
  become: true
  vars:
    git_repo: https://github.com/<username>/portfolio.git
    dest: /var/www/portfolio

  tasks:
  - name: Clone GitHub repository
    git:
      repo: "{{ git_repo }}"
      dest: "{{ dest }}"
      version: master
      force: yes

  - name: Install dependencies
    apt:
      name: python3-pip
   
  - name: Install python modules
    pip:
      name: -r {{ dest }}/requirements.txt

  - name: Copy the configuration file
    template:
      src: templates/config.j2
      dest: /etc/nginx/sites-available/portfolio.conf

  - name: Enable the virtual host
    file:
      src: /etc/nginx/sites-available/portfolio.conf
      dest: /etc/nginx/sites-enabled/portfolio.conf
      state: link

  - name: Restart nginx
    service:
      name: nginx
      state: restarted

